CREATE TABLE wallets (
    owner BIGINT REFERENCES usuarios(id) UNIQUE PRIMARY KEY,
    balance DOUBLE PRECISION NOT NULL DEFAULT(0),
    not_available DOUBLE PRECISION NOT NULL DEFAULT(0),
    balance_to_sell DOUBLE PRECISION NOT NULL DEFAULT(0)
);